# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
fastlane_version "2.121.1"
xcversion(version: "11.0")

platform :ios do
  desc "Clean project"
  lane :clean do
    xcclean(workspace: "Emotion.xcworkspace", scheme: "Emotion")
  end

  desc "Build project"
  lane :build do
    xcbuild(archive: false, workspace: "Emotion.xcworkspace", scheme: "Emotion")
  end

end
